name: wiwmedia_wiwsport_v3
description: Second Version of WIWMOBILE APP

version: 32.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.19.0
  social_embed_webview: ^0.2.1+9
  firebase_analytics: ^5.0.11
  firebase_admob: ^0.11.0+1
  flutter_native_admob: ^2.1.0+3
  onesignal_flutter: ^2.6.1
  flutter_inappwebview: ^4.0.0+4
  universal_html: ^1.2.3
  http: ^0.12.0+2
  youtube_player_flutter: ^7.0.0+7
  flutter_youtube_view: ^1.1.10
  cached_network_image: ^2.2.0+1
  webview_flutter: ^0.3.14+1
  uni_links: ^0.2.0
  settings_ui: ^0.5.0
  admob_flutter: ^0.3.1
  connectivity: ^0.4.8+2
  flutter_widget_from_html: ^0.5.1+5
  cupertino_icons: ^1.0.0
  share: ^0.6.4+3
  twitter_api: ^0.1.2
  tweet_webview: ^0.2.2
  flutter_linkify: ^4.0.2
  flutter_parsed_text: ^1.2.0
  carousel_pro: ^1.0.0
  #video_viewer: ^1.0.9
  shimmer: ^1.1.2
  native_video_view: ^0.3.0
  inview_notifier_list: ^1.0.0
  scrollable_positioned_list: ^0.1.10
  html_unescape: ^1.0.2
  #video_player: ^1.0.1
  #chewie: ^0.12.2
  getwidget: ^1.0.7
  meedu_player: ^0.4.3
  cloud_firestore: ^0.16.0+1
  firebase_core: ^0.7.0
  #google_mobile_ads: ^0.11.0+4
  #google_mobile_ads: ^1.1.0
  mixpanel_flutter: ^1.0.0
  overlay_screen: ^1.2.0+1
  firebase_auth: ^0.20.1
  provider:
  google_sign_in:
  #flutter_facebook_auth: ^1.0.0
  flutter_facebook_login: ^3.0.0
  pinput: ^0.2.6
  #audioplayers:
  firebase_storage: ^7.0.0
  flutter_audio_recorder: ^0.5.5
  path_provider:
  audio_recorder: ^1.0.2
  just_audio: ^0.6.15+1
  #audio_session: ^0.0.11
  bubble: ^1.1.9+1
  audio_video_progress_bar: ^0.1.0
  audioplayer: ^0.8.1
  audioplayer_web: 0.7.1
  flutter_portal: ^0.3.0
  assets_audio_player: ^2.0.15
  uuid: ^2.2.2
  audioplayers: ^0.14.2
  shared_preferences: ^0.5.12+4
  country_list_pick: ^1.0.1+3
  focus_detector: ^1.1.0+1
  youtube_plyr_iframe: ^1.3.7

  mailer: ^3.3.0
  ads: ^2.2.0
  page_transition: ^1.1.7+6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.8.0"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: ""

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/audios/
    - assets/icons/
    - assets/images/
    - assets/gifs/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
